Models/Challenge.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Reflection;

namespace CodeChecker.Models
{
    public enum ChallengeStatus
    {
        [Description("Not Submitted")]
        NotSubmitted,
        [Description("In Progress")]
        InProgress,
        Failed,
        Pass
    }

    public static class Extensions
    {
        public static string GetDescription(this Enum value)
        {
            Type type = value.GetType();
            string? name = Enum.GetName(type, value);
            if (name != null)
            {
                FieldInfo? field = type.GetField(name);
                if (field != null)
                {
                    DescriptionAttribute? attr =
                           Attribute.GetCustomAttribute(field,
                             typeof(DescriptionAttribute)) as DescriptionAttribute;
                    if (attr != null)
                    {
                        return attr.Description;
                    }
                }
                return name;
            }
            return "";
        }
    }

    public class ChallengeBaseInfo
    {
        public int Id { get; set; }
        public string ChallengeName { get; set; } = null;
        public double Difficulty { get; set; }


        public ChallengeBaseInfo() { }

        public ChallengeBaseInfo(int anId, string aChallengeName, double aDifficulty)
        {
            Id = anId;
            ChallengeName = aChallengeName;
            Difficulty = aDifficulty;
        }

        public string DifficultyFancyFormat()
        {
            return string.Format("{0:0.0}", Difficulty);
        }
    }

    public class ChallengeFullInfo : ChallengeBaseInfo
    {
        public string AuthorName { get; set; } = null!;

        public string Description { get; set; } = null!;
    }

    public class ChallengeSubmission
    {
        public int Id { get; set; }
        public required IFormFile File { get; set; }
    }
}

Models/ChallengeTestCase.cs
using System;
using System.Collections.Generic;

namespace CodeChecker.Models;

public partial class ChallengeTestCase
{
    public int Id { get; set; }

    public string TestCases { get; set; } = null!;

    public virtual ChallengeFullInfo IdNavigation { get; set; } = null!;
}

Models/CodecheckerContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CodeChecker.Models;

public partial class CodecheckerContext : DbContext
{
    public CodecheckerContext()
    {
    }

    public CodecheckerContext(DbContextOptions<CodecheckerContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ChallengeFullInfo> ChallengeData { get; set; }

    public virtual DbSet<ChallengeTestCase> ChallengeTestCases { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ChallengeFullInfo>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AuthorName)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.ChallengeName)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Description).HasColumnType("text");
        });

        modelBuilder.Entity<ChallengeTestCase>(entity =>
        {
            entity.HasNoKey();

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.HasOne(d => d.IdNavigation).WithMany()
                .HasForeignKey(d => d.Id)
                .HasConstraintName("FK_ChallengeID");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

Models/DatabaseContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CodeChecker.Models;

public partial class DatabaseContext : DbContext
{
    public DbSet<ChallengeFullInfo> ChallengeData { get; set; }
    public DbSet<ChallengeTestCase> ChallengeTestCases { get; set; }

    public DatabaseContext() { }

    public DatabaseContext(DbContextOptions<DatabaseContext> options) : base(options) { }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ChallengeFullInfo>(entity =>
        {
            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AuthorName)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.ChallengeName)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Description).HasColumnType("text");
        });

        modelBuilder.Entity<ChallengeTestCase>(entity =>
        {
            entity.HasNoKey();

            entity.Property(e => e.Id).HasColumnName("ID");

            entity.HasOne(d => d.IdNavigation).WithMany()
                .HasForeignKey(d => d.Id)
                .HasConstraintName("FK_ChallengeID");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

Models/ErrorViewModel.cs
namespace CodeChecker.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ChallengeController.cs
using CodeChecker.Models;
using Microsoft.AspNetCore.Mvc;

namespace CodeChecker.Controllers
{
    public class ChallengeController : Controller
    {
        private readonly DatabaseContext _context;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly string[] _allowedExtensions = { ".cpp", ".java", ".cs", ".py" };
        public ChallengeController(DatabaseContext aContext, IWebHostEnvironment aWebHostEnvironment)
        {
            _context = aContext;
            _hostingEnvironment = aWebHostEnvironment;
        }

        [HttpGet]
        public IActionResult ChallengeSubmission(int aChallengeId)
        {
            ViewBag.ChallengeData = _context.ChallengeData.Where(c => c.Id == aChallengeId).First();
            ViewBag.ErrorString = TempData["ErrorString"]?.ToString();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ChallengeSubmission(ChallengeSubmission aSubmission)
        {
            if(aSubmission.File.Equals(null))
                return ReturnError("No file submitted", aSubmission.Id);

            int index = aSubmission.File.FileName.LastIndexOf(".");
            if(index < 0)
                return ReturnError("Incorrect file type uploaded", aSubmission.Id);

            string fileType = aSubmission.File.FileName.Substring(index);
            if(index < 0 || _allowedExtensions.Contains(fileType) == false)
                return ReturnError("Incorrect file type uploaded", aSubmission.Id);


            string path = Path.Combine(_hostingEnvironment.ContentRootPath, "UploadedSubmissions");
            if (System.IO.Directory.Exists(path) == false)
                System.IO.Directory.CreateDirectory(path);

            string newFileName = aSubmission.Id + "-" + DateTime.Now.ToString("yyyy-dd-m--HH-mm-ss") + fileType;
            string filePath = Path.Combine(path, newFileName);

            using (Stream fileStream = new FileStream(filePath, FileMode.Create))
            {
                await aSubmission.File.CopyToAsync(fileStream);
            }

            return Redirect("/");
        }

        private RedirectToActionResult ReturnError(string anErrorString, int anId)
        {
            TempData["ErrorString"] = anErrorString;
            return RedirectToAction("ChallengeSubmission", new { aChallengeId = anId });
        }
    }
}

Controllers/HomeController.cs
using CodeChecker.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace CodeChecker.Controllers
{    public class HomeController : Controller
    {
        private readonly DatabaseContext _context;
        public HomeController(DatabaseContext aContext)
        {
            _context = aContext;
            ViewBag.Title = "Home Page";
        }

        public IActionResult Index()
        {
            IEnumerable<ChallengeBaseInfo> displayInfo = _context.ChallengeData
                            .Select(c => new ChallengeBaseInfo(c.Id, c.ChallengeName, c.Difficulty));
            return View(displayInfo);
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

Views/Challenge/ChallengeSubmission.cshtml
@model ChallengeSubmission

@{
    ViewData["Title"] = ViewBag.ChallengeData.ChallengeName;
}

@section CustomStyle
{
    <style>
        #ChallengeDisplay{
            border: solid black;
            border-width: thin;
            border-radius: 25px;
            background-color: lightyellow;
        }
        #DifficultyBubble
        {
            background-color: lightgreen;
            margin-top: 10%;
            border-radius: 30px;
            padding: 10px 30px;
            display:inline-block;
        }
        #ChallengeDescription
        {
            padding: 0px 3%;
        }
        #Submission
        {
            background-color: lightgray;
            border-radius: 10px;
            margin-left: 15px;
        }
        .Error
        {
            color: red;
            font: italic;
            text-align: center;
            display: table;
            margin: 0 auto;
            height: 30px;
        }
    </style>
}

<div class="container">
    <div class="row">
        <div class="col-md-8" id="ChallengeDisplay">
            <div class="row">
                <div style="width: 66.66666667%;">
                    <h1 class="display-4">@ViewBag.ChallengeData.ChallengeName</h1>
                    <h6 style="padding-left: 15px">Submitted by: @ViewBag.ChallengeData.AuthorName</h6>
                </div>
                <div style="width: 33.33333333%;">
                    <div class="float-end" id="DifficultyBubble">
                        @ViewBag.ChallengeData.DifficultyFancyFormat()
                    </div>
                </div>
            </div>
            <hr />
            <div class="row" id="ChallengeDescription">
                <p>@ViewBag.ChallengeData.Description</p>
            </div>
        </div>
        <div class="col-md-3" id="Submission">
            <div class="Error">@ViewBag.ErrorString</div>

            <h6>Accepted file types:</h6>
            <p><i>.cs | .cpp | .java | .py</i></p>
            <form enctype="multipart/form-data" asp-action="ChallengeSubmission" method="post">
                <input type="file" asp-for="@Model.File" accept=".cs, .cpp, .java, .py" required/>
                <input type="hidden" asp-for="@Model.Id" value="@ViewBag.ChallengeData.Id"/>
                <input style="margin-top: 10px" type="submit" value="Submit"/>
            </form>
        </div>
    </div>
</div>

Views/Challenge/Display.cshtml
@model ChallengeSubmission

@{
    ViewData["Title"] = ViewBag.ChallengeData.ChallengeName;
}

@section CustomStyle
{
    <style>
        #ChallengeDisplay{
            border: solid black;
            border-width: thin;
            border-radius: 25px;
            background-color: lightyellow;
        }
        #DifficultyBubble
        {
            background-color: lightgreen;
            margin-top: 10%;
            border-radius: 30px;
            padding: 10px 30px;
            display:inline-block;
        }
        #ChallengeDescription
        {
            padding: 0px 3%;
        }
        #Submission
        {
            background-color: lightgray;
            border-radius: 10px;
            margin-left: 15px;
        }
    </style>
}

<div class="container">
    <div class="row">
        <div class="col-md-8" id="ChallengeDisplay">
            <div class="row">
                <div style="width: 66.66666667%;">
                    <h1 class="display-4">@ViewBag.ChallengeData.ChallengeName</h1>
                    <h6 style="padding-left: 15px">Submitted by: @ViewBag.ChallengeData.AuthorName</h6>
                </div>
                <div style="width: 33.33333333%;">
                    <div class="float-end" id="DifficultyBubble">
                        @ViewBag.ChallengeData.DifficultyFancyFormat()
                    </div>
                </div>
            </div>
            <hr />
            <div class="row" id="ChallengeDescription">
                <p>@ViewBag.ChallengeData.Description</p>
            </div>
        </div>
        <div class="col-md-3" id="Submission">
            <br />
            <h6>Accepted file types:</h6>
            <p><i>.cs | .cpp | .java | .py</i></p>
            <form enctype="multipart/form-data" asp-action="SubmitFile" method="post">
                <input type="file" asp-for="@Model.File" accept=".cs, .cpp, .java, .py" required/>
                <input type="hidden" asp-for="@Model.Id" value="@ViewBag.ChallengeData.Id"/>
                <input type="submit" value="Submit"/>
            </form>
        </div>
    </div>
</div>

Views/Home/Index.cshtml
@model IEnumerable<ChallengeBaseInfo>

@{
    ViewData["Title"] = "Home Page";
}

@section CustomStyle
{
    <style>
        #MainTable tr.body:hover { background-color: lightyellow; }
    </style>
}

<div class="text-center">
    <h1 class="display-4">Welcome to Programming Challenges!</h1>
    <table class="table mt-5" id="MainTable">
        <thead>
            <tr>
                <th>Difficulty</th>
                <th>Challenge Name</th>
                <th>Challenge Id</th>
            </tr>
        </thead>
        <tbody>
            @foreach (ChallengeBaseInfo challenge in Model)
            {
                <tr class="body" onclick="location.href='@Url.ActionLink("ChallengeSubmission", "Challenge", new { aChallengeId = challenge.Id })'">
                    <td>@challenge.DifficultyFancyFormat()</td>
                    <td>@challenge.ChallengeName</td>
                    <td>@challenge.Id</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CodeChecker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CodeChecker.styles.css" asp-append-version="true" />
    @RenderSection("CustomStyle", required:false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CodeChecker</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CodeChecker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>